### ISSUE TITLE
make entire inline comment clickable

### ISSUE THREAD

**Issue by nschloe** [paperhub/paperhub-frontend#102]
The click should always expand the reply slot, not lead to the user page.

**Comment by andrenarchy** [comment]
+1! I clicked the link a hundred times unintentionally and had to go back to the article page. Annoyance++! Instead of directly redirecting to the user page, we could open a modal window with a bit more information about the user (à la twitter). We could then place the actual link in this modal.

**Comment by nschloe** [comment]
> Instead of directly redirecting to the user page, we could open a modal window with a bit more 
> information about the user (à la twitter).

Maybe we don't even need to make the display name clickable at all. After all, it's a tiny inline snippet.

**Comment by andrenarchy** [comment]
-1! ;) You should be able to get a link to the user page everywhere this user left a trace.

**Comment by andrenarchy** [comment]
fixed via #105
