### ISSUE TITLE
Edit my profile button appears with navigation style in mobile view

### ISSUE THREAD

**Issue by andrenarchy** [paperhub/paperhub-frontend#43]
![bildschirmfoto vom 2015-02-24 14 02 11](https://cloud.githubusercontent.com/assets/1874116/6349729/c0210454-bc2d-11e4-9e57-8a26e229cd0c.png)

The button should appear as a regular button like in the desktop view:
![bildschirmfoto vom 2015-02-24 14 02 34](https://cloud.githubusercontent.com/assets/1874116/6349741/e9200fc6-bc2d-11e4-8fdc-b84eefc3a02b.png)

@pure180 do you have an idea how to fix this in a clean way?

**Comment by pure180** [comment]
yes, i do. you need to change the depending classes in the less files, use
```css
.ph-header-submenu-container .btn-default {
    ....
}
.ph-header-submenu-container .btn-default,
.ph-header-submenu-container .navbar-collapse {
    ...
}
```
instead of:
```less
.ph-header .btn-default {
    ....
}
.ph-header .btn-default,
.ph-header .navbar-collapse {
    ...
}
```
