### ISSUE TITLE
sync from ORCID doesn't work anymore

### ISSUE THREAD

**Issue by nschloe** [paperhub/paperhub-frontend#81]
```
TypeError: Cannot read property 'id' of undefined
```
![id_of_undef](https://cloud.githubusercontent.com/assets/181628/6601730/98b649ba-c817-11e4-8934-596250cafc56.png)

**Comment by andrenarchy** [comment]
Fixed in backend 9dd58de3acfcb6a4c6c49ae616adfb1f51f61b0f.
