### ISSUE TITLE
'require' is not defined

### ISSUE THREAD

**Issue by nschloe** [paperhub/paperhub-frontend#85]
Using `strict` mode (issue #84) in the JS brought up a general issue:
> This is because require() does not exist in the browser/client-side JavaScript.

(from http://stackoverflow.com/a/19059825/353337).

We should probably review or use of `require` on the client side with respect to [CommonJS](http://en.wikipedia.org/wiki/CommonJS), [RequireJS](http://requirejs.org/docs/whyamd.html), [Browserify](http://browserify.org/), ...

Helpful could be http://procbits.com/2013/06/17/client-side-javascript-management-browserify-vs-component.

**Comment by andrenarchy** [comment]
fixed in d44ad876e46ed72fcf699f4d87dcc3d929b57d3b
